name: equations_solver
description: An equation-solving application that uses the API of the 'equations' package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  equations:
    path: ../../

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.7
  go_router: ^10.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/
    - assets/svg/
