name: equations
description: An equation-solving library that also works with complex numbers and fractions.
version: 5.0.1
repository: https://github.com/albertodev01/equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ^3.0.0

dependencies:
  fraction: ^5.0.1
  petitparser: ^5.4.0

dev_dependencies:
  test: ^1.24.4
  