name: equations
description: An equation-solving library that also works with complex numbers and fractions.
version: 5.0.2
repository: https://github.com/albertodev01/equations
homepage: https://pub.dev/packages/equations

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  fraction: ^5.0.2
  petitparser: ^6.0.2

dev_dependencies:
  test: ^1.25.5

topics:
  - equations
  - numbers
  - algebra
